using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SolvencyII.Validation.Model
{
    public class EvalResult
    {
        public long INSTANCE { get; set; }
        public long PK_ID { get; set; }
        public string CONTEXT { get; set; }

        public int TotalFormula { get; set; }

        public string E1_FORMULA { get; set; }
        public string E2_FORMULA { get; set; }
        public string E3_FORMULA { get; set; }
        public string E4_FORMULA { get; set; }
        public string E5_FORMULA { get; set; }
        public string E6_FORMULA { get; set; }
        public string E7_FORMULA { get; set; }
        public string E8_FORMULA { get; set; }
        public string E9_FORMULA { get; set; }
        public string E10_FORMULA { get; set; }
        public string E11_FORMULA { get; set; }
        public string E12_FORMULA { get; set; }
        public string E13_FORMULA { get; set; }
        public string E14_FORMULA { get; set; }
        public string E15_FORMULA { get; set; }
        public string E16_FORMULA { get; set; }
        public string E17_FORMULA { get; set; }
        public string E18_FORMULA { get; set; }
        public string E19_FORMULA { get; set; }
        public string E20_FORMULA { get; set; }
        public string E21_FORMULA { get; set; }
        public string E22_FORMULA { get; set; }
        public string E23_FORMULA { get; set; }
        public string E24_FORMULA { get; set; }
        public string E25_FORMULA { get; set; }
        public string E26_FORMULA { get; set; }
        public string E27_FORMULA { get; set; }
        public string E28_FORMULA { get; set; }
        public string E29_FORMULA { get; set; }
        public string E30_FORMULA { get; set; }
        public string E31_FORMULA { get; set; }
        public string E32_FORMULA { get; set; }
        public string E33_FORMULA { get; set; }
        public string E34_FORMULA { get; set; }
        public string E35_FORMULA { get; set; }
        public string E36_FORMULA { get; set; }
        public string E37_FORMULA { get; set; }
        public string E38_FORMULA { get; set; }
        public string E39_FORMULA { get; set; }
        public string E40_FORMULA { get; set; }
        public string E41_FORMULA { get; set; }
        public string E42_FORMULA { get; set; }
        public string E43_FORMULA { get; set; }
        public string E44_FORMULA { get; set; }
        public string E45_FORMULA { get; set; }
        public string E46_FORMULA { get; set; }
        public string E47_FORMULA { get; set; }
        public string E48_FORMULA { get; set; }
        public string E49_FORMULA { get; set; }
        public string E50_FORMULA { get; set; }
        public string E51_FORMULA { get; set; }
        public string E52_FORMULA { get; set; }
        public string E53_FORMULA { get; set; }
        public string E54_FORMULA { get; set; }
        public string E55_FORMULA { get; set; }
        public string E56_FORMULA { get; set; }
        public string E57_FORMULA { get; set; }
        public string E58_FORMULA { get; set; }
        public string E59_FORMULA { get; set; }
        public string E60_FORMULA { get; set; }
        public string E61_FORMULA { get; set; }
        public string E62_FORMULA { get; set; }
        public string E63_FORMULA { get; set; }
        public string E64_FORMULA { get; set; }
        public string E65_FORMULA { get; set; }
        public string E66_FORMULA { get; set; }
        public string E67_FORMULA { get; set; }
        public string E68_FORMULA { get; set; }
        public string E69_FORMULA { get; set; }
        public string E70_FORMULA { get; set; }
        public string E71_FORMULA { get; set; }
        public string E72_FORMULA { get; set; }
        public string E73_FORMULA { get; set; }
        public string E74_FORMULA { get; set; }
        public string E75_FORMULA { get; set; }
        public string E76_FORMULA { get; set; }
        public string E77_FORMULA { get; set; }
        public string E78_FORMULA { get; set; }
        public string E79_FORMULA { get; set; }
        public string E80_FORMULA { get; set; }
        public string E81_FORMULA { get; set; }
        public string E82_FORMULA { get; set; }
        public string E83_FORMULA { get; set; }
        public string E84_FORMULA { get; set; }
        public string E85_FORMULA { get; set; }
        public string E86_FORMULA { get; set; }
        public string E87_FORMULA { get; set; }
        public string E88_FORMULA { get; set; }
        public string E89_FORMULA { get; set; }
        public string E90_FORMULA { get; set; }
        public string E91_FORMULA { get; set; }
        public string E92_FORMULA { get; set; }
        public string E93_FORMULA { get; set; }
        public string E94_FORMULA { get; set; }
        public string E95_FORMULA { get; set; }
        public string E96_FORMULA { get; set; }
        public string E97_FORMULA { get; set; }
        public string E98_FORMULA { get; set; }
        public string E99_FORMULA { get; set; }
        public string E100_FORMULA { get; set; }
        public string E101_FORMULA { get; set; }
        public string E102_FORMULA { get; set; }
        public string E103_FORMULA { get; set; }
        public string E104_FORMULA { get; set; }
        public string E105_FORMULA { get; set; }
        public string E106_FORMULA { get; set; }
        public string E107_FORMULA { get; set; }
        public string E108_FORMULA { get; set; }
        public string E109_FORMULA { get; set; }
        public string E110_FORMULA { get; set; }
        public string E111_FORMULA { get; set; }
        public string E112_FORMULA { get; set; }
        public string E113_FORMULA { get; set; }
        public string E114_FORMULA { get; set; }
        public string E115_FORMULA { get; set; }
        public string E116_FORMULA { get; set; }
        public string E117_FORMULA { get; set; }
        public string E118_FORMULA { get; set; }
        public string E119_FORMULA { get; set; }
        public string E120_FORMULA { get; set; }
        public string E121_FORMULA { get; set; }
        public string E122_FORMULA { get; set; }
        public string E123_FORMULA { get; set; }
        public string E124_FORMULA { get; set; }
        public string E125_FORMULA { get; set; }
        public string E126_FORMULA { get; set; }
        public string E127_FORMULA { get; set; }
        public string E128_FORMULA { get; set; }
        public string E129_FORMULA { get; set; }
        public string E130_FORMULA { get; set; }
        public string E131_FORMULA { get; set; }
        public string E132_FORMULA { get; set; }
        public string E133_FORMULA { get; set; }
        public string E134_FORMULA { get; set; }
        public string E135_FORMULA { get; set; }
        public string E136_FORMULA { get; set; }
        public string E137_FORMULA { get; set; }
        public string E138_FORMULA { get; set; }
        public string E139_FORMULA { get; set; }
        public string E140_FORMULA { get; set; }
        public string E141_FORMULA { get; set; }
        public string E142_FORMULA { get; set; }
        public string E143_FORMULA { get; set; }
        public string E144_FORMULA { get; set; }
        public string E145_FORMULA { get; set; }
        public string E146_FORMULA { get; set; }
        public string E147_FORMULA { get; set; }
        public string E148_FORMULA { get; set; }
        public string E149_FORMULA { get; set; }
        public string E150_FORMULA { get; set; }
        public string E151_FORMULA { get; set; }
        public string E152_FORMULA { get; set; }
        public string E153_FORMULA { get; set; }
        public string E154_FORMULA { get; set; }
        public string E155_FORMULA { get; set; }
        public string E156_FORMULA { get; set; }
        public string E157_FORMULA { get; set; }
        public string E158_FORMULA { get; set; }
        public string E159_FORMULA { get; set; }
        public string E160_FORMULA { get; set; }
		public string E1_L { get; set; }
        public string E2_L { get; set; }
        public string E3_L { get; set; }
        public string E4_L { get; set; }
        public string E5_L { get; set; }
        public string E6_L { get; set; }
        public string E7_L { get; set; }
        public string E8_L { get; set; }
        public string E9_L { get; set; }
        public string E10_L { get; set; }
        public string E11_L { get; set; }
        public string E12_L { get; set; }
        public string E13_L { get; set; }
        public string E14_L { get; set; }
        public string E15_L { get; set; }
        public string E16_L { get; set; }
        public string E17_L { get; set; }
        public string E18_L { get; set; }
        public string E19_L { get; set; }
        public string E20_L { get; set; }
        public string E21_L { get; set; }
        public string E22_L { get; set; }
        public string E23_L { get; set; }
        public string E24_L { get; set; }
        public string E25_L { get; set; }
        public string E26_L { get; set; }
        public string E27_L { get; set; }
        public string E28_L { get; set; }
        public string E29_L { get; set; }
        public string E30_L { get; set; }
        public string E31_L { get; set; }
        public string E32_L { get; set; }
        public string E33_L { get; set; }
        public string E34_L { get; set; }
        public string E35_L { get; set; }
        public string E36_L { get; set; }
        public string E37_L { get; set; }
        public string E38_L { get; set; }
        public string E39_L { get; set; }
        public string E40_L { get; set; }
        public string E41_L { get; set; }
        public string E42_L { get; set; }
        public string E43_L { get; set; }
        public string E44_L { get; set; }
        public string E45_L { get; set; }
        public string E46_L { get; set; }
        public string E47_L { get; set; }
        public string E48_L { get; set; }
        public string E49_L { get; set; }
        public string E50_L { get; set; }
        public string E51_L { get; set; }
        public string E52_L { get; set; }
        public string E53_L { get; set; }
        public string E54_L { get; set; }
        public string E55_L { get; set; }
        public string E56_L { get; set; }
        public string E57_L { get; set; }
        public string E58_L { get; set; }
        public string E59_L { get; set; }
        public string E60_L { get; set; }
        public string E61_L { get; set; }
        public string E62_L { get; set; }
        public string E63_L { get; set; }
        public string E64_L { get; set; }
        public string E65_L { get; set; }
        public string E66_L { get; set; }
        public string E67_L { get; set; }
        public string E68_L { get; set; }
        public string E69_L { get; set; }
        public string E70_L { get; set; }
        public string E71_L { get; set; }
        public string E72_L { get; set; }
        public string E73_L { get; set; }
        public string E74_L { get; set; }
        public string E75_L { get; set; }
        public string E76_L { get; set; }
        public string E77_L { get; set; }
        public string E78_L { get; set; }
        public string E79_L { get; set; }
        public string E80_L { get; set; }
        public string E81_L { get; set; }
        public string E82_L { get; set; }
        public string E83_L { get; set; }
        public string E84_L { get; set; }
        public string E85_L { get; set; }
        public string E86_L { get; set; }
        public string E87_L { get; set; }
        public string E88_L { get; set; }
        public string E89_L { get; set; }
        public string E90_L { get; set; }
        public string E91_L { get; set; }
        public string E92_L { get; set; }
        public string E93_L { get; set; }
        public string E94_L { get; set; }
        public string E95_L { get; set; }
        public string E96_L { get; set; }
        public string E97_L { get; set; }
        public string E98_L { get; set; }
        public string E99_L { get; set; }
        public string E100_L { get; set; }
        public string E101_L { get; set; }
        public string E102_L { get; set; }
        public string E103_L { get; set; }
        public string E104_L { get; set; }
        public string E105_L { get; set; }
        public string E106_L { get; set; }
        public string E107_L { get; set; }
        public string E108_L { get; set; }
        public string E109_L { get; set; }
        public string E110_L { get; set; }
        public string E111_L { get; set; }
        public string E112_L { get; set; }
        public string E113_L { get; set; }
        public string E114_L { get; set; }
        public string E115_L { get; set; }
        public string E116_L { get; set; }
        public string E117_L { get; set; }
        public string E118_L { get; set; }
        public string E119_L { get; set; }
        public string E120_L { get; set; }
        public string E121_L { get; set; }
        public string E122_L { get; set; }
        public string E123_L { get; set; }
        public string E124_L { get; set; }
        public string E125_L { get; set; }
        public string E126_L { get; set; }
        public string E127_L { get; set; }
        public string E128_L { get; set; }
        public string E129_L { get; set; }
        public string E130_L { get; set; }
        public string E131_L { get; set; }
        public string E132_L { get; set; }
        public string E133_L { get; set; }
        public string E134_L { get; set; }
        public string E135_L { get; set; }
        public string E136_L { get; set; }
        public string E137_L { get; set; }
        public string E138_L { get; set; }
        public string E139_L { get; set; }
        public string E140_L { get; set; }
        public string E141_L { get; set; }
        public string E142_L { get; set; }
        public string E143_L { get; set; }
        public string E144_L { get; set; }
        public string E145_L { get; set; }
        public string E146_L { get; set; }
        public string E147_L { get; set; }
        public string E148_L { get; set; }
        public string E149_L { get; set; }
        public string E150_L { get; set; }
        public string E151_L { get; set; }
        public string E152_L { get; set; }
        public string E153_L { get; set; }
        public string E154_L { get; set; }
        public string E155_L { get; set; }
        public string E156_L { get; set; }
        public string E157_L { get; set; }
        public string E158_L { get; set; }
        public string E159_L { get; set; }
        public string E160_L { get; set; }
		public string E1_R { get; set; }
        public string E2_R { get; set; }
        public string E3_R { get; set; }
        public string E4_R { get; set; }
        public string E5_R { get; set; }
        public string E6_R { get; set; }
        public string E7_R { get; set; }
        public string E8_R { get; set; }
        public string E9_R { get; set; }
        public string E10_R { get; set; }
        public string E11_R { get; set; }
        public string E12_R { get; set; }
        public string E13_R { get; set; }
        public string E14_R { get; set; }
        public string E15_R { get; set; }
        public string E16_R { get; set; }
        public string E17_R { get; set; }
        public string E18_R { get; set; }
        public string E19_R { get; set; }
        public string E20_R { get; set; }
        public string E21_R { get; set; }
        public string E22_R { get; set; }
        public string E23_R { get; set; }
        public string E24_R { get; set; }
        public string E25_R { get; set; }
        public string E26_R { get; set; }
        public string E27_R { get; set; }
        public string E28_R { get; set; }
        public string E29_R { get; set; }
        public string E30_R { get; set; }
        public string E31_R { get; set; }
        public string E32_R { get; set; }
        public string E33_R { get; set; }
        public string E34_R { get; set; }
        public string E35_R { get; set; }
        public string E36_R { get; set; }
        public string E37_R { get; set; }
        public string E38_R { get; set; }
        public string E39_R { get; set; }
        public string E40_R { get; set; }
        public string E41_R { get; set; }
        public string E42_R { get; set; }
        public string E43_R { get; set; }
        public string E44_R { get; set; }
        public string E45_R { get; set; }
        public string E46_R { get; set; }
        public string E47_R { get; set; }
        public string E48_R { get; set; }
        public string E49_R { get; set; }
        public string E50_R { get; set; }
        public string E51_R { get; set; }
        public string E52_R { get; set; }
        public string E53_R { get; set; }
        public string E54_R { get; set; }
        public string E55_R { get; set; }
        public string E56_R { get; set; }
        public string E57_R { get; set; }
        public string E58_R { get; set; }
        public string E59_R { get; set; }
        public string E60_R { get; set; }
        public string E61_R { get; set; }
        public string E62_R { get; set; }
        public string E63_R { get; set; }
        public string E64_R { get; set; }
        public string E65_R { get; set; }
        public string E66_R { get; set; }
        public string E67_R { get; set; }
        public string E68_R { get; set; }
        public string E69_R { get; set; }
        public string E70_R { get; set; }
        public string E71_R { get; set; }
        public string E72_R { get; set; }
        public string E73_R { get; set; }
        public string E74_R { get; set; }
        public string E75_R { get; set; }
        public string E76_R { get; set; }
        public string E77_R { get; set; }
        public string E78_R { get; set; }
        public string E79_R { get; set; }
        public string E80_R { get; set; }
        public string E81_R { get; set; }
        public string E82_R { get; set; }
        public string E83_R { get; set; }
        public string E84_R { get; set; }
        public string E85_R { get; set; }
        public string E86_R { get; set; }
        public string E87_R { get; set; }
        public string E88_R { get; set; }
        public string E89_R { get; set; }
        public string E90_R { get; set; }
        public string E91_R { get; set; }
        public string E92_R { get; set; }
        public string E93_R { get; set; }
        public string E94_R { get; set; }
        public string E95_R { get; set; }
        public string E96_R { get; set; }
        public string E97_R { get; set; }
        public string E98_R { get; set; }
        public string E99_R { get; set; }
        public string E100_R { get; set; }
        public string E101_R { get; set; }
        public string E102_R { get; set; }
        public string E103_R { get; set; }
        public string E104_R { get; set; }
        public string E105_R { get; set; }
        public string E106_R { get; set; }
        public string E107_R { get; set; }
        public string E108_R { get; set; }
        public string E109_R { get; set; }
        public string E110_R { get; set; }
        public string E111_R { get; set; }
        public string E112_R { get; set; }
        public string E113_R { get; set; }
        public string E114_R { get; set; }
        public string E115_R { get; set; }
        public string E116_R { get; set; }
        public string E117_R { get; set; }
        public string E118_R { get; set; }
        public string E119_R { get; set; }
        public string E120_R { get; set; }
        public string E121_R { get; set; }
        public string E122_R { get; set; }
        public string E123_R { get; set; }
        public string E124_R { get; set; }
        public string E125_R { get; set; }
        public string E126_R { get; set; }
        public string E127_R { get; set; }
        public string E128_R { get; set; }
        public string E129_R { get; set; }
        public string E130_R { get; set; }
        public string E131_R { get; set; }
        public string E132_R { get; set; }
        public string E133_R { get; set; }
        public string E134_R { get; set; }
        public string E135_R { get; set; }
        public string E136_R { get; set; }
        public string E137_R { get; set; }
        public string E138_R { get; set; }
        public string E139_R { get; set; }
        public string E140_R { get; set; }
        public string E141_R { get; set; }
        public string E142_R { get; set; }
        public string E143_R { get; set; }
        public string E144_R { get; set; }
        public string E145_R { get; set; }
        public string E146_R { get; set; }
        public string E147_R { get; set; }
        public string E148_R { get; set; }
        public string E149_R { get; set; }
        public string E150_R { get; set; }
        public string E151_R { get; set; }
        public string E152_R { get; set; }
        public string E153_R { get; set; }
        public string E154_R { get; set; }
        public string E155_R { get; set; }
        public string E156_R { get; set; }
        public string E157_R { get; set; }
        public string E158_R { get; set; }
        public string E159_R { get; set; }
        public string E160_R { get; set; }
    }
}
