using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SolvencyII.Validation.Model
{
    public class EvalResult
    {
        public long INSTANCE{get;set;}
        public long PK_ID { get; set; }
        public string CONTEXT{get;set;}

        public int TotalFormula { get; set; }

        public string E1_FORMULA { get; set; }
        public string E2_FORMULA { get; set; }
        public string E3_FORMULA { get; set; }
        public string E4_FORMULA { get; set; }
        public string E5_FORMULA { get; set; }
        public string E6_FORMULA { get; set; }
        public string E7_FORMULA { get; set; }
        public string E8_FORMULA { get; set; }
        public string E9_FORMULA { get; set; }
        public string E10_FORMULA { get; set; }
        public string E11_FORMULA { get; set; }
        public string E12_FORMULA { get; set; }
        public string E13_FORMULA { get; set; }
        public string E14_FORMULA { get; set; }
        public string E15_FORMULA { get; set; }
        public string E16_FORMULA { get; set; }
        public string E17_FORMULA { get; set; }
        public string E18_FORMULA { get; set; }
        public string E19_FORMULA { get; set; }
        public string E20_FORMULA { get; set; }
        public string E21_FORMULA { get; set; }
        public string E22_FORMULA { get; set; }
        public string E23_FORMULA { get; set; }
        public string E24_FORMULA { get; set; }
        public string E25_FORMULA { get; set; }
        public string E26_FORMULA { get; set; }
        public string E27_FORMULA { get; set; }
        public string E28_FORMULA { get; set; }
        public string E29_FORMULA { get; set; }
        public string E30_FORMULA { get; set; }
        public string E31_FORMULA { get; set; }
        public string E32_FORMULA { get; set; }
        public string E33_FORMULA { get; set; }
        public string E34_FORMULA { get; set; }
        public string E35_FORMULA { get; set; }
        public string E36_FORMULA { get; set; }
        public string E37_FORMULA { get; set; }
        public string E38_FORMULA { get; set; }
        public string E39_FORMULA { get; set; }
        public string E40_FORMULA { get; set; }
        public string E41_FORMULA { get; set; }
        public string E42_FORMULA { get; set; }
        public string E43_FORMULA { get; set; }
        public string E44_FORMULA { get; set; }
        public string E45_FORMULA { get; set; }
        public string E46_FORMULA { get; set; }
        public string E47_FORMULA { get; set; }
        public string E48_FORMULA { get; set; }
        public string E49_FORMULA { get; set; }
        public string E50_FORMULA { get; set; }
        public string E51_FORMULA { get; set; }
        public string E52_FORMULA { get; set; }
        public string E53_FORMULA { get; set; }
        public string E54_FORMULA { get; set; }
        public string E55_FORMULA { get; set; }
        public string E56_FORMULA { get; set; }
        public string E57_FORMULA { get; set; }
        public string E58_FORMULA { get; set; }
        public string E59_FORMULA { get; set; }
        public string E60_FORMULA { get; set; }
        public string E61_FORMULA { get; set; }
        public string E62_FORMULA { get; set; }
        public string E63_FORMULA { get; set; }
        public string E64_FORMULA { get; set; }
        public string E65_FORMULA { get; set; }
        public string E66_FORMULA { get; set; }
        public string E67_FORMULA { get; set; }
        public string E68_FORMULA { get; set; }
        public string E69_FORMULA { get; set; }
        public string E70_FORMULA { get; set; }
        public string E71_FORMULA { get; set; }
        public string E72_FORMULA { get; set; }
        public string E73_FORMULA { get; set; }
        public string E74_FORMULA { get; set; }
        public string E75_FORMULA { get; set; }
        public string E76_FORMULA { get; set; }
        public string E77_FORMULA { get; set; }
        public string E78_FORMULA { get; set; }
        public string E79_FORMULA { get; set; }
        public string E80_FORMULA { get; set; }
        public string E81_FORMULA { get; set; }
        public string E82_FORMULA { get; set; }
        public string E83_FORMULA { get; set; }
        public string E84_FORMULA { get; set; }
        public string E85_FORMULA { get; set; }
        public string E86_FORMULA { get; set; }
        public string E87_FORMULA { get; set; }
        public string E88_FORMULA { get; set; }
        public string E89_FORMULA { get; set; }
        public string E90_FORMULA { get; set; }
        public string E91_FORMULA { get; set; }
        public string E92_FORMULA { get; set; }
        public string E93_FORMULA { get; set; }
        public string E94_FORMULA { get; set; }
        public string E95_FORMULA { get; set; }
        public string E96_FORMULA { get; set; }
        public string E97_FORMULA { get; set; }
        public string E98_FORMULA { get; set; }
        public string E99_FORMULA { get; set; }
        public string E100_FORMULA { get; set; }
        public string E101_FORMULA { get; set; }
        public string E102_FORMULA { get; set; }
        public string E103_FORMULA { get; set; }
        public string E104_FORMULA { get; set; }
        public string E105_FORMULA { get; set; }
        public string E106_FORMULA { get; set; }
        public string E107_FORMULA { get; set; }
        public string E108_FORMULA { get; set; }
        public string E109_FORMULA { get; set; }
        public string E110_FORMULA { get; set; }
        public string E111_FORMULA { get; set; }
        public string E112_FORMULA { get; set; }
        public string E113_FORMULA { get; set; }
        public string E114_FORMULA { get; set; }
        public string E115_FORMULA { get; set; }
        public string E116_FORMULA { get; set; }
        public string E117_FORMULA { get; set; }
        public string E118_FORMULA { get; set; }
        public string E119_FORMULA { get; set; }
        public string E120_FORMULA { get; set; }
        public string E121_FORMULA { get; set; }
        public string E122_FORMULA { get; set; }
        public string E123_FORMULA { get; set; }
        public string E124_FORMULA { get; set; }
        public string E125_FORMULA { get; set; }
        public string E126_FORMULA { get; set; }
        public string E127_FORMULA { get; set; }
        public string E128_FORMULA { get; set; }
        public string E129_FORMULA { get; set; }
        public string E130_FORMULA { get; set; }
        public string E131_FORMULA { get; set; }
        public string E132_FORMULA { get; set; }
        public string E133_FORMULA { get; set; }
        public string E134_FORMULA { get; set; }
        public string E135_FORMULA { get; set; }
        public string E136_FORMULA { get; set; }
        public string E137_FORMULA { get; set; }
        public string E138_FORMULA { get; set; }
        public string E139_FORMULA { get; set; }
        public string E140_FORMULA { get; set; }
        public string E141_FORMULA { get; set; }
        public string E142_FORMULA { get; set; }
        public string E143_FORMULA { get; set; }
        public string E144_FORMULA { get; set; }
        public string E145_FORMULA { get; set; }
        public string E146_FORMULA { get; set; }
        public string E147_FORMULA { get; set; }
        public string E148_FORMULA { get; set; }
        public string E149_FORMULA { get; set; }
        public string E150_FORMULA { get; set; }
        public string E151_FORMULA { get; set; }
        public string E152_FORMULA { get; set; }
        public string E153_FORMULA { get; set; }
        public string E154_FORMULA { get; set; }
        public string E155_FORMULA { get; set; }
        public string E156_FORMULA { get; set; }
        public string E157_FORMULA { get; set; }
        public string E158_FORMULA { get; set; }
        public string E159_FORMULA { get; set; }
        public string E160_FORMULA { get; set; }

    }
}
