//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dFact
    {
        public long FactID { get; set; }
        public long InstanceID { get; set; }
        public string DataPointSignature { get; set; }
        public string Unit { get; set; }
        public string Decimals { get; set; }
        public Nullable<double> NumericValue { get; set; }
        public Nullable<System.DateTime> DateTimeValue { get; set; }
        public Nullable<bool> BooleanValue { get; set; }
        public string TextValue { get; set; }
    }
}
