//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dInstance()
        {
            this.dInstanceLargeDimensionMembers = new HashSet<dInstanceLargeDimensionMember>();
        }
    
        public long InstanceID { get; set; }
        public long ModuleID { get; set; }
        public string FileName { get; set; }
        public byte[] CompressedFileBlob { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string EntityScheme { get; set; }
        public string EntityIdentifier { get; set; }
        public string EntityName { get; set; }
        public Nullable<System.DateTime> PeriodEndDateOrInstant { get; set; }
        public string EntityCurrency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dInstanceLargeDimensionMember> dInstanceLargeDimensionMembers { get; set; }
    }
}
