//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPMdb : DbContext
    {
        public DPMdb()
            : base("name=DPMdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aApplication> aApplications { get; set; }
        public virtual DbSet<aInterfaceComponent> aInterfaceComponents { get; set; }
        public virtual DbSet<dFact> dFacts { get; set; }
        public virtual DbSet<dFilingIndicator> dFilingIndicators { get; set; }
        public virtual DbSet<dInstance> dInstances { get; set; }
        public virtual DbSet<dInstanceLargeDimensionMember> dInstanceLargeDimensionMembers { get; set; }
        public virtual DbSet<dMessage> dMessages { get; set; }
        public virtual DbSet<mAxi> mAxis { get; set; }
        public virtual DbSet<mAxisOrdinate> mAxisOrdinates { get; set; }
        public virtual DbSet<mConcept> mConcepts { get; set; }
        public virtual DbSet<mConceptTranslation> mConceptTranslations { get; set; }
        public virtual DbSet<mConceptualModule> mConceptualModules { get; set; }
        public virtual DbSet<mDimension> mDimensions { get; set; }
        public virtual DbSet<mDomain> mDomains { get; set; }
        public virtual DbSet<mHierarchy> mHierarchies { get; set; }
        public virtual DbSet<mHierarchyNode> mHierarchyNodes { get; set; }
        public virtual DbSet<mLanguage> mLanguages { get; set; }
        public virtual DbSet<mMember> mMembers { get; set; }
        public virtual DbSet<mMetric> mMetrics { get; set; }
        public virtual DbSet<mModule> mModules { get; set; }
        public virtual DbSet<mModuleBusinessTemplate> mModuleBusinessTemplates { get; set; }
        public virtual DbSet<mOpenAxisValueRestriction> mOpenAxisValueRestrictions { get; set; }
        public virtual DbSet<mOrdinateCategorisation> mOrdinateCategorisations { get; set; }
        public virtual DbSet<mOwner> mOwners { get; set; }
        public virtual DbSet<mReference> mReferences { get; set; }
        public virtual DbSet<mReferenceCategorisation> mReferenceCategorisations { get; set; }
        public virtual DbSet<mReportingFramework> mReportingFrameworks { get; set; }
        public virtual DbSet<mTable> mTables { get; set; }
        public virtual DbSet<mTableAxi> mTableAxis { get; set; }
        public virtual DbSet<mTableCell> mTableCells { get; set; }
        public virtual DbSet<mTaxonomy> mTaxonomies { get; set; }
        public virtual DbSet<mTaxonomyTable> mTaxonomyTables { get; set; }
        public virtual DbSet<mTemplateOrTable> mTemplateOrTables { get; set; }
        public virtual DbSet<SQLITEADMIN_QUERIES> SQLITEADMIN_QUERIES { get; set; }
        public virtual DbSet<vExpression> vExpressions { get; set; }
        public virtual DbSet<vValidationRule> vValidationRules { get; set; }
        public virtual DbSet<vVariableOfExpression> vVariableOfExpressions { get; set; }
        public virtual DbSet<dMessageReference> dMessageReferences { get; set; }
        public virtual DbSet<vwGetAllHierarchy> vwGetAllHierarchies { get; set; }
        public virtual DbSet<vwGetControlInformation> vwGetControlInformations { get; set; }
        public virtual DbSet<vwGetInstanceDropDownData> vwGetInstanceDropDownDatas { get; set; }
        public virtual DbSet<vwGetLanguageInfo> vwGetLanguageInfoes { get; set; }
        public virtual DbSet<vwGetOrdinateDimension> vwGetOrdinateDimensions { get; set; }
        public virtual DbSet<vwGetOrdinateHierarchyID_HD> vwGetOrdinateHierarchyID_HD { get; set; }
        public virtual DbSet<vwGetOrdinateHierarchyID_MD> vwGetOrdinateHierarchyID_MD { get; set; }
        public virtual DbSet<vwGetOrdinateType> vwGetOrdinateTypes { get; set; }
        public virtual DbSet<vwGetTableAxisOrdinateColumn> vwGetTableAxisOrdinateColumns { get; set; }
        public virtual DbSet<vwGetTableControlDetail> vwGetTableControlDetails { get; set; }
        public virtual DbSet<vwGetTableControlDetailsZDim> vwGetTableControlDetailsZDims { get; set; }
        public virtual DbSet<vwGetTableName> vwGetTableNames { get; set; }
        public virtual DbSet<vwGetTreeData> vwGetTreeDatas { get; set; }
        public virtual DbSet<vwGetTreeDataZDimChildren> vwGetTreeDataZDimChildrens { get; set; }
        public virtual DbSet<vwGetzAxisMember> vwGetzAxisMembers { get; set; }
        public virtual DbSet<vwGetZDimTreeTable> vwGetZDimTreeTables { get; set; }
        public virtual DbSet<vwHierarchyLookupAxi> vwHierarchyLookupAxis { get; set; }
        public virtual DbSet<vwHierarchyLookupMetric> vwHierarchyLookupMetrics { get; set; }
    }
}
