//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAxisOrdinate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mAxisOrdinate()
        {
            this.mAxisOrdinate1 = new HashSet<mAxisOrdinate>();
            this.mOrdinateCategorisations = new HashSet<mOrdinateCategorisation>();
            this.mTableCells = new HashSet<mTableCell>();
        }
    
        public Nullable<long> AxisID { get; set; }
        public long OrdinateID { get; set; }
        public string OrdinateLabel { get; set; }
        public string OrdinateCode { get; set; }
        public Nullable<bool> IsDisplayBeforeChildren { get; set; }
        public Nullable<bool> IsAbstractHeader { get; set; }
        public Nullable<bool> IsRowKey { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> ParentOrdinateID { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string TypeOfKey { get; set; }
    
        public virtual mAxi mAxi { get; set; }
        public virtual mConcept mConcept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAxisOrdinate> mAxisOrdinate1 { get; set; }
        public virtual mAxisOrdinate mAxisOrdinate2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mOrdinateCategorisation> mOrdinateCategorisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTableCell> mTableCells { get; set; }
    }
}
