//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mConcept
    {
        public mConcept()
        {
            this.mAxisOrdinates = new HashSet<mAxisOrdinate>();
            this.mConceptTranslations = new HashSet<mConceptTranslation>();
            this.mDimensions = new HashSet<mDimension>();
            this.mDomains = new HashSet<mDomain>();
            this.mHierarchies = new HashSet<mHierarchy>();
            this.mHierarchyNodes = new HashSet<mHierarchyNode>();
            this.mLanguages = new HashSet<mLanguage>();
            this.mMembers = new HashSet<mMember>();
            this.mOwners = new HashSet<mOwner>();
            this.mReportingFrameworks = new HashSet<mReportingFramework>();
            this.mTables = new HashSet<mTable>();
            this.mTaxonomies = new HashSet<mTaxonomy>();
            this.mTemplateOrTables = new HashSet<mTemplateOrTable>();
            this.vValidationRules = new HashSet<vValidationRule>();
            this.mReferences = new HashSet<mReference>();
        }
    
        public long ConceptID { get; set; }
        public string ConceptType { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual ICollection<mAxisOrdinate> mAxisOrdinates { get; set; }
        public virtual mOwner mOwner { get; set; }
        public virtual ICollection<mConceptTranslation> mConceptTranslations { get; set; }
        public virtual ICollection<mDimension> mDimensions { get; set; }
        public virtual ICollection<mDomain> mDomains { get; set; }
        public virtual ICollection<mHierarchy> mHierarchies { get; set; }
        public virtual ICollection<mHierarchyNode> mHierarchyNodes { get; set; }
        public virtual ICollection<mLanguage> mLanguages { get; set; }
        public virtual ICollection<mMember> mMembers { get; set; }
        public virtual ICollection<mOwner> mOwners { get; set; }
        public virtual ICollection<mReportingFramework> mReportingFrameworks { get; set; }
        public virtual ICollection<mTable> mTables { get; set; }
        public virtual ICollection<mTaxonomy> mTaxonomies { get; set; }
        public virtual ICollection<mTemplateOrTable> mTemplateOrTables { get; set; }
        public virtual ICollection<vValidationRule> vValidationRules { get; set; }
        public virtual ICollection<mReference> mReferences { get; set; }
    }
}
