//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mConceptTranslation
    {
        public long ConceptID { get; set; }
        public long LanguageID { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public string Text { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual mOwner mOwner { get; set; }
        public virtual mLanguage mLanguage { get; set; }
    }
}
