//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mDomain
    {
        public mDomain()
        {
            this.mDimensions = new HashSet<mDimension>();
            this.mHierarchies = new HashSet<mHierarchy>();
            this.mMembers = new HashSet<mMember>();
            this.mMetrics = new HashSet<mMetric>();
        }
    
        public long DomainID { get; set; }
        public string DomainCode { get; set; }
        public string DomainLabel { get; set; }
        public string DomainDescription { get; set; }
        public string DomainXBRLCode { get; set; }
        public string DataType { get; set; }
        public Nullable<bool> IsTypedDomain { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual ICollection<mDimension> mDimensions { get; set; }
        public virtual ICollection<mHierarchy> mHierarchies { get; set; }
        public virtual ICollection<mMember> mMembers { get; set; }
        public virtual ICollection<mMetric> mMetrics { get; set; }
    }
}
