//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mHierarchyNode
    {
        public long HierarchyID { get; set; }
        public long MemberID { get; set; }
        public Nullable<bool> IsAbstract { get; set; }
        public string ComparisonOperator { get; set; }
        public string UnaryOperator { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> ParentMemberID { get; set; }
        public string HierarchyNodeLabel { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string Path { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual mHierarchy mHierarchy { get; set; }
        public virtual mMember mMember { get; set; }
    }
}
