//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMetric
    {
        public long MetricID { get; set; }
        public Nullable<long> CorrespondingMemberID { get; set; }
        public string DataType { get; set; }
        public string FlowType { get; set; }
        public string BalanceType { get; set; }
        public Nullable<long> ReferencedDomainID { get; set; }
        public Nullable<long> ReferencedHierarchyID { get; set; }
        public Nullable<long> HierarchyStartingMemberID { get; set; }
        public Nullable<bool> IsStartingMemberIncluded { get; set; }
    
        public virtual mDomain mDomain { get; set; }
        public virtual mHierarchy mHierarchy { get; set; }
        public virtual mMember mMember { get; set; }
        public virtual mMember mMember1 { get; set; }
    }
}
