//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mModule()
        {
            this.mModuleBusinessTemplates = new HashSet<mModuleBusinessTemplate>();
            this.mDimensions = new HashSet<mDimension>();
            this.vValidationRules = new HashSet<vValidationRule>();
        }
    
        public long ModuleID { get; set; }
        public Nullable<long> TaxonomyID { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleLabel { get; set; }
        public Nullable<long> ConceptualModuleID { get; set; }
        public string DefaultFrequency { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string XBRLSchemaRef { get; set; }
    
        public virtual mConceptualModule mConceptualModule { get; set; }
        public virtual mTaxonomy mTaxonomy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mModuleBusinessTemplate> mModuleBusinessTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mDimension> mDimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vValidationRule> vValidationRules { get; set; }
    }
}
