//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mTable()
        {
            this.mTableAxis = new HashSet<mTableAxi>();
            this.mTableCells = new HashSet<mTableCell>();
            this.mTaxonomyTables = new HashSet<mTaxonomyTable>();
            this.vValidationRules = new HashSet<vValidationRule>();
        }
    
        public long TableID { get; set; }
        public string TableCode { get; set; }
        public string TableLabel { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string XbrlFilingIndicatorCode { get; set; }
        public string XbrlTableCode { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string YDimVal { get; set; }
        public string ZDimVal { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTableAxi> mTableAxis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTableCell> mTableCells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTaxonomyTable> mTaxonomyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vValidationRule> vValidationRules { get; set; }
    }
}
