//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mTemplateOrTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mTemplateOrTable()
        {
            this.mTaxonomyTables = new HashSet<mTaxonomyTable>();
            this.mTemplateOrTable1 = new HashSet<mTemplateOrTable>();
        }
    
        public long TemplateOrTableID { get; set; }
        public Nullable<long> TaxonomyID { get; set; }
        public string TemplateOrTableCode { get; set; }
        public string TemplateOrTableLabel { get; set; }
        public string TemplateOrTableType { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> ParentTemplateOrTableID { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string TC { get; set; }
        public string TT { get; set; }
        public string TL { get; set; }
        public string TD { get; set; }
        public string YC { get; set; }
        public string XC { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual mTaxonomy mTaxonomy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTaxonomyTable> mTaxonomyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mTemplateOrTable> mTemplateOrTable1 { get; set; }
        public virtual mTemplateOrTable mTemplateOrTable2 { get; set; }
    }
}
