//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExpression
    {
        public vExpression()
        {
            this.vValidationRules = new HashSet<vValidationRule>();
            this.vVariableOfExpressions = new HashSet<vVariableOfExpression>();
            this.vValidationRules1 = new HashSet<vValidationRule>();
        }
    
        public long ExpressionID { get; set; }
        public string ExpressionType { get; set; }
        public string TableBasedFormula { get; set; }
        public string LogicalExpression { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual ICollection<vValidationRule> vValidationRules { get; set; }
        public virtual ICollection<vVariableOfExpression> vVariableOfExpressions { get; set; }
        public virtual ICollection<vValidationRule> vValidationRules1 { get; set; }
    }
}
