//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetTableAxisOrdinateColumn
    {
        public Nullable<long> AxisID { get; set; }
        public long OrdinateID { get; set; }
        public Nullable<bool> IsRowKey { get; set; }
        public Nullable<long> Order { get; set; }
        public long TableID { get; set; }
        public string OrdinateCode { get; set; }
        public long TableAxisOrder { get; set; }
        public Nullable<long> OrdinateOrder { get; set; }
        public long LanguageID { get; set; }
    }
}
