//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetTableControlDetail
    {
        public long CellID { get; set; }
        public Nullable<bool> IsShaded { get; set; }
        public long XordinateID { get; set; }
        public long YordinateID { get; set; }
        public string TableCellSignature { get; set; }
        public Nullable<long> TableID { get; set; }
    }
}
