//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetControlInformation
    {
        public long OrdinateID { get; set; }
        public string OrdinateLabel { get; set; }
        public string AxisOrientation { get; set; }
        public long AxisID { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> Level { get; set; }
        public long TableID { get; set; }
        public Nullable<bool> IsAbstractHeader { get; set; }
        public Nullable<long> ParentOrdinateID { get; set; }
        public Nullable<bool> IsDisplayBeforeChildren { get; set; }
        public string OrdinateCode { get; set; }
        public Nullable<long> ParentOrder { get; set; }
    }
}
