//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwHierarchyLookupAxi
    {
        public long AxisID { get; set; }
        public long HierarchyID { get; set; }
        public string OwnerPrefix { get; set; }
        public string DomainCode { get; set; }
        public string MemberCode { get; set; }
    }
}
