//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class aApplication
    {
        public aApplication()
        {
            this.aInterfaceComponents = new HashSet<aInterfaceComponent>();
        }
    
        public long ApplicationID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationVersion { get; set; }
        public string DatabaseType { get; set; }
    
        public virtual ICollection<aInterfaceComponent> aInterfaceComponents { get; set; }
    }
}
