//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPMdb : DbContext
    {
        public DPMdb()
            : base("name=DPMdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aApplication> aApplications { get; set; }
        public DbSet<aInterfaceComponent> aInterfaceComponents { get; set; }
        public DbSet<dAvailableTable> dAvailableTables { get; set; }
        public DbSet<dFact> dFacts { get; set; }
        public DbSet<dFilingIndicator> dFilingIndicators { get; set; }
        public DbSet<dInstance> dInstances { get; set; }
        public DbSet<dMessage> dMessages { get; set; }
        public DbSet<dProcessingContext> dProcessingContexts { get; set; }
        public DbSet<dProcessingFact> dProcessingFacts { get; set; }
        public DbSet<mAxi> mAxis { get; set; }
        public DbSet<mAxisOrdinate> mAxisOrdinates { get; set; }
        public DbSet<mConcept> mConcepts { get; set; }
        public DbSet<mConceptTranslation> mConceptTranslations { get; set; }
        public DbSet<mConceptualModule> mConceptualModules { get; set; }
        public DbSet<mDimension> mDimensions { get; set; }
        public DbSet<mDomain> mDomains { get; set; }
        public DbSet<mHierarchy> mHierarchies { get; set; }
        public DbSet<mHierarchyNode> mHierarchyNodes { get; set; }
        public DbSet<mLanguage> mLanguages { get; set; }
        public DbSet<mMember> mMembers { get; set; }
        public DbSet<mMetric> mMetrics { get; set; }
        public DbSet<mModule> mModules { get; set; }
        public DbSet<mModuleBusinessTemplate> mModuleBusinessTemplates { get; set; }
        public DbSet<mOpenAxisValueRestriction> mOpenAxisValueRestrictions { get; set; }
        public DbSet<mOrdinateCategorisation> mOrdinateCategorisations { get; set; }
        public DbSet<mOwner> mOwners { get; set; }
        public DbSet<mReference> mReferences { get; set; }
        public DbSet<mReferenceCategorisation> mReferenceCategorisations { get; set; }
        public DbSet<mReportingFramework> mReportingFrameworks { get; set; }
        public DbSet<mTable> mTables { get; set; }
        public DbSet<mTableAxi> mTableAxis { get; set; }
        public DbSet<mTableCell> mTableCells { get; set; }
        public DbSet<mTableDimensionSet> mTableDimensionSets { get; set; }
        public DbSet<mTaxonomy> mTaxonomies { get; set; }
        public DbSet<mTaxonomyTable> mTaxonomyTables { get; set; }
        public DbSet<mTemplateOrTable> mTemplateOrTables { get; set; }
        public DbSet<SQLITEADMIN_QUERIES> SQLITEADMIN_QUERIES { get; set; }
        public DbSet<vExpression> vExpressions { get; set; }
        public DbSet<vValidationRule> vValidationRules { get; set; }
        public DbSet<vVariableOfExpression> vVariableOfExpressions { get; set; }
        public DbSet<dMessageReference> dMessageReferences { get; set; }
        public DbSet<vwGetAllHierarchy> vwGetAllHierarchies { get; set; }
        public DbSet<vwGetControlInformation> vwGetControlInformations { get; set; }
        public DbSet<vwGetInstanceDropDownData> vwGetInstanceDropDownDatas { get; set; }
        public DbSet<vwGetLanguageInfo> vwGetLanguageInfoes { get; set; }
        public DbSet<vwGetOrdinateDimension> vwGetOrdinateDimensions { get; set; }
        public DbSet<vwGetOrdinateHierarchyID_HD> vwGetOrdinateHierarchyID_HD { get; set; }
        public DbSet<vwGetOrdinateHierarchyID_MD> vwGetOrdinateHierarchyID_MD { get; set; }
        public DbSet<vwGetOrdinateType> vwGetOrdinateTypes { get; set; }
        public DbSet<vwGetTableAxisOrdinateColumn> vwGetTableAxisOrdinateColumns { get; set; }
        public DbSet<vwGetTableControlDetail> vwGetTableControlDetails { get; set; }
        public DbSet<vwGetTableControlDetailsZDim> vwGetTableControlDetailsZDims { get; set; }
        public DbSet<vwGetTableName> vwGetTableNames { get; set; }
        public DbSet<vwGetTreeData> vwGetTreeDatas { get; set; }
        public DbSet<vwGetTreeDataZDimChildren> vwGetTreeDataZDimChildrens { get; set; }
        public DbSet<vwGetzAxisMember> vwGetzAxisMembers { get; set; }
        public DbSet<vwGetZDimTreeTable> vwGetZDimTreeTables { get; set; }
        public DbSet<vwHierarchyLookupAxi> vwHierarchyLookupAxis { get; set; }
        public DbSet<vwHierarchyLookupMetric> vwHierarchyLookupMetrics { get; set; }
    }
}
