//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAxi
    {
        public mAxi()
        {
            this.mAxisOrdinates = new HashSet<mAxisOrdinate>();
            this.mOpenAxisValueRestrictions = new HashSet<mOpenAxisValueRestriction>();
            this.mTableAxis = new HashSet<mTableAxi>();
        }
    
        public long AxisID { get; set; }
        public string AxisOrientation { get; set; }
        public string AxisLabel { get; set; }
        public Nullable<bool> IsOpenAxis { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual ICollection<mAxisOrdinate> mAxisOrdinates { get; set; }
        public virtual ICollection<mOpenAxisValueRestriction> mOpenAxisValueRestrictions { get; set; }
        public virtual ICollection<mTableAxi> mTableAxis { get; set; }
    }
}
