//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMember
    {
        public mMember()
        {
            this.mHierarchyNodes = new HashSet<mHierarchyNode>();
            this.mMetrics = new HashSet<mMetric>();
            this.mMetrics1 = new HashSet<mMetric>();
            this.mOpenAxisValueRestrictions = new HashSet<mOpenAxisValueRestriction>();
            this.mOrdinateCategorisations = new HashSet<mOrdinateCategorisation>();
            this.mReferenceCategorisations = new HashSet<mReferenceCategorisation>();
        }
    
        public long MemberID { get; set; }
        public Nullable<long> DomainID { get; set; }
        public string MemberCode { get; set; }
        public string MemberLabel { get; set; }
        public string MemberXBRLCode { get; set; }
        public Nullable<bool> IsDefaultMember { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual mDomain mDomain { get; set; }
        public virtual ICollection<mHierarchyNode> mHierarchyNodes { get; set; }
        public virtual ICollection<mMetric> mMetrics { get; set; }
        public virtual ICollection<mMetric> mMetrics1 { get; set; }
        public virtual ICollection<mOpenAxisValueRestriction> mOpenAxisValueRestrictions { get; set; }
        public virtual ICollection<mOrdinateCategorisation> mOrdinateCategorisations { get; set; }
        public virtual ICollection<mReferenceCategorisation> mReferenceCategorisations { get; set; }
    }
}
