//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mModule
    {
        public mModule()
        {
            this.mModuleBusinessTemplates = new HashSet<mModuleBusinessTemplate>();
            this.mTableDimensionSets = new HashSet<mTableDimensionSet>();
            this.vValidationRules = new HashSet<vValidationRule>();
        }
    
        public long ModuleID { get; set; }
        public Nullable<long> TaxonomyID { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleLabel { get; set; }
        public Nullable<long> ConceptualModuleID { get; set; }
        public string DefaultFrequency { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string XBRLSchemaRef { get; set; }
    
        public virtual mConceptualModule mConceptualModule { get; set; }
        public virtual mTaxonomy mTaxonomy { get; set; }
        public virtual ICollection<mModuleBusinessTemplate> mModuleBusinessTemplates { get; set; }
        public virtual ICollection<mTableDimensionSet> mTableDimensionSets { get; set; }
        public virtual ICollection<vValidationRule> vValidationRules { get; set; }
    }
}
