//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2DPM.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetOrdinateHierarchyID_MD
    {
        public long OrdinateID { get; set; }
        public Nullable<long> ReferencedDomainID { get; set; }
        public Nullable<long> HierarchyID { get; set; }
        public Nullable<long> HierarchyStartingMemberID { get; set; }
        public Nullable<bool> IsStartingMemberIncluded { get; set; }
    }
}
