//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAxis
    {
        public mAxis()
        {
            this.mAxisOrdinate = new HashSet<mAxisOrdinate>();
            this.mOpenAxisValueRestriction = new HashSet<mOpenAxisValueRestriction>();
            this.mTable = new HashSet<mTable>();
        }
    
        public long AxisID { get; set; }
        public string AxisOrientation { get; set; }
        public string AxisLabel { get; set; }
        public Nullable<long> AxisOrder { get; set; }
        public Nullable<bool> IsOpenAxis { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual ICollection<mAxisOrdinate> mAxisOrdinate { get; set; }
        public virtual ICollection<mOpenAxisValueRestriction> mOpenAxisValueRestriction { get; set; }
        public virtual ICollection<mTable> mTable { get; set; }
    }
}
