//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mDomain
    {
        public mDomain()
        {
            this.mDimension = new HashSet<mDimension>();
            this.mHierarchy = new HashSet<mHierarchy>();
            this.mMember = new HashSet<mMember>();
            this.mMetric = new HashSet<mMetric>();
        }
    
        public long DomainID { get; set; }
        public string DomainCode { get; set; }
        public string DomainLabel { get; set; }
        public string DomainDescription { get; set; }
        public string DomainXBRLCode { get; set; }
        public string DataType { get; set; }
        public Nullable<bool> IsTypedDomain { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual ICollection<mDimension> mDimension { get; set; }
        public virtual ICollection<mHierarchy> mHierarchy { get; set; }
        public virtual ICollection<mMember> mMember { get; set; }
        public virtual ICollection<mMetric> mMetric { get; set; }
    }
}
