//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mTableCell
    {
        public mTableCell()
        {
            this.mAxisOrdinate = new HashSet<mAxisOrdinate>();
            this.mReference = new HashSet<mReference>();
        }
    
        public long CellID { get; set; }
        public Nullable<long> TableID { get; set; }
        public Nullable<long> IsRowKey { get; set; }
        public Nullable<long> IsShaded { get; set; }
        public string BusinessCode { get; set; }
        public string DatapointSignature { get; set; }
    
        public virtual mTable mTable { get; set; }
        public virtual ICollection<mAxisOrdinate> mAxisOrdinate { get; set; }
        public virtual ICollection<mReference> mReference { get; set; }
    }
}
