//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vValidationRule
    {
        public vValidationRule()
        {
            this.vValidationRuleSets = new HashSet<vValidationRuleSet>();
            this.vValidationScopes = new HashSet<vValidationScope>();
            this.vExpressions = new HashSet<vExpression>();
        }
    
        public long ValidationRuleID { get; set; }
        public string ValidationCode { get; set; }
        public string Severity { get; set; }
        public string Scope { get; set; }
        public string ValidationType { get; set; }
        public Nullable<long> ExpressionID { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual vExpression vExpression { get; set; }
        public virtual ICollection<vValidationRuleSet> vValidationRuleSets { get; set; }
        public virtual ICollection<vValidationScope> vValidationScopes { get; set; }
        public virtual ICollection<vExpression> vExpressions { get; set; }
    }
}
