//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class dInstance
    {
        public long InstanceID { get; set; }
        public long ModuleID { get; set; }
        public string FileName { get; set; }
        public byte[] CompressedFileBlob { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string EntityScheme { get; set; }
        public string EntityIdentifier { get; set; }
        public string EntityName { get; set; }
        public Nullable<System.DateTime> PeriodEndDateOrInstant { get; set; }
        public string EntityCurrency { get; set; }
    }
}
