//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class dProcessingFact
    {
        public long InstanceID { get; set; }
        public string Metric { get; set; }
        public string ContextID { get; set; }
        public string ValueTxt { get; set; }
        public Nullable<double> ValueDecimal { get; set; }
        public Nullable<double> ValueDate { get; set; }
        public string Error { get; set; }
    }
}
