//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAxisOrdinate
    {
        public mAxisOrdinate()
        {
            this.mAxisOrdinate1 = new HashSet<mAxisOrdinate>();
            this.mOrdinateCategorisation = new HashSet<mOrdinateCategorisation>();
            this.mTableCell = new HashSet<mTableCell>();
        }
    
        public Nullable<long> AxisID { get; set; }
        public int OrdinateID { get; set; }
        public string OrdinateLabel { get; set; }
        public string OrdinateCode { get; set; }
        public bool IsDisplayBeforeChildren { get; set; }
        public bool IsAbstractHeader { get; set; }
        public Nullable<bool> IsRowKey { get; set; }
        public Nullable<long> Level { get; set; }
        public long Order { get; set; }
        public Nullable<long> ParentOrdinateID { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public Nullable<long> TableAxisOrder { get; set; }
        public Nullable<long> OrdinateOrder { get; set; }
        public string AxisOrientation { get; set; }
        public string TopBranchOrder { get; set; }

        public virtual mAxis mAxis { get; set; }
        public virtual ICollection<mAxisOrdinate> mAxisOrdinate1 { get; set; }
        public virtual mAxisOrdinate mAxisOrdinate2 { get; set; }
        public virtual ICollection<mOrdinateCategorisation> mOrdinateCategorisation { get; set; }
        public virtual ICollection<mTableCell> mTableCell { get; set; }

        

    }
}
