//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mBusinessTemplateOrTable
    {
        public mBusinessTemplateOrTable()
        {
            this.mBusinessTemplateOrTable1 = new HashSet<mBusinessTemplateOrTable>();
            this.mModuleBusinessTemplate = new HashSet<mModuleBusinessTemplate>();
        }
    
        public long BusinessTemplateOrTableID { get; set; }
        public Nullable<long> TaxonomyID { get; set; }
        public string BusinessTemplateOrTableCode { get; set; }
        public string BusinessTemplateOrTableLabel { get; set; }
        public string BusinessTemplateOrTableType { get; set; }
        public Nullable<long> Order { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> ParentBusinessTemplateOrTableID { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string LocationRange { get; set; }
    
        public virtual mTaxonomy mTaxonomy { get; set; }
        public virtual ICollection<mBusinessTemplateOrTable> mBusinessTemplateOrTable1 { get; set; }
        public virtual mBusinessTemplateOrTable mBusinessTemplateOrTable2 { get; set; }
        public virtual mConcept mConcept { get; set; }
        public virtual ICollection<mModuleBusinessTemplate> mModuleBusinessTemplate { get; set; }
    }
}
