//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mConcept
    {
        public mConcept()
        {
            this.mBusinessTemplateOrTable = new HashSet<mBusinessTemplateOrTable>();
            this.mConceptTranslation = new HashSet<mConceptTranslation>();
            this.mDimension = new HashSet<mDimension>();
            this.mDomain = new HashSet<mDomain>();
            this.mHierarchy = new HashSet<mHierarchy>();
            this.mLanguage = new HashSet<mLanguage>();
            this.mMember = new HashSet<mMember>();
            this.mOwner1 = new HashSet<mOwner>();
            this.mReportingFramework = new HashSet<mReportingFramework>();
            this.mTaxonomy = new HashSet<mTaxonomy>();
            this.mTemplateOrTable = new HashSet<mTemplateOrTable>();
            this.vValidationRule = new HashSet<vValidationRule>();
            this.mReference = new HashSet<mReference>();
        }
    
        public long ConceptID { get; set; }
        public string ConceptType { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual ICollection<mBusinessTemplateOrTable> mBusinessTemplateOrTable { get; set; }
        public virtual mOwner mOwner { get; set; }
        public virtual ICollection<mConceptTranslation> mConceptTranslation { get; set; }
        public virtual ICollection<mDimension> mDimension { get; set; }
        public virtual ICollection<mDomain> mDomain { get; set; }
        public virtual ICollection<mHierarchy> mHierarchy { get; set; }
        public virtual ICollection<mLanguage> mLanguage { get; set; }
        public virtual ICollection<mMember> mMember { get; set; }
        public virtual ICollection<mOwner> mOwner1 { get; set; }
        public virtual ICollection<mReportingFramework> mReportingFramework { get; set; }
        public virtual ICollection<mTaxonomy> mTaxonomy { get; set; }
        public virtual ICollection<mTemplateOrTable> mTemplateOrTable { get; set; }
        public virtual ICollection<vValidationRule> vValidationRule { get; set; }
        public virtual ICollection<mReference> mReference { get; set; }
    }
}
