//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mHierarchy
    {
        public mHierarchy()
        {
            this.mHierarchyNode = new HashSet<mHierarchyNode>();
            this.mMetric = new HashSet<mMetric>();
        }
    
        public long HierarchyID { get; set; }
        public string HierarchyCode { get; set; }
        public string HierarchyLabel { get; set; }
        public Nullable<long> DomainID { get; set; }
        public string HierarchyDescription { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual mConcept mConcept { get; set; }
        public virtual mDomain mDomain { get; set; }
        public virtual ICollection<mHierarchyNode> mHierarchyNode { get; set; }
        public virtual ICollection<mMetric> mMetric { get; set; }
    }
}
