//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mOpenAxisValueRestriction
    {
        public long AxisID { get; set; }
        public long HierarchyID { get; set; }
        public long HierarchyStartingMemberID { get; set; }
        public Nullable<bool> IsStartingMemberIncluded { get; set; }
    
        public virtual mAxis mAxis { get; set; }
    }
}
