//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mOwner
    {
        public mOwner()
        {
            this.mConcept = new HashSet<mConcept>();
            this.mConceptTranslation = new HashSet<mConceptTranslation>();
            this.mOwner1 = new HashSet<mOwner>();
        }
    
        public long OwnerID { get; set; }
        public string OwnerName { get; set; }
        public string OwnerNamespace { get; set; }
        public string OwnerLocation { get; set; }
        public string OwnerPrefix { get; set; }
        public string OwnerCopyright { get; set; }
        public Nullable<long> ParentOwnerID { get; set; }
        public Nullable<long> ConceptID { get; set; }
    
        public virtual ICollection<mConcept> mConcept { get; set; }
        public virtual mConcept mConcept1 { get; set; }
        public virtual ICollection<mConceptTranslation> mConceptTranslation { get; set; }
        public virtual ICollection<mOwner> mOwner1 { get; set; }
        public virtual mOwner mOwner2 { get; set; }
    }
}
