//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvencyII.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mTable
    {
        public mTable()
        {
            this.dAvailableTable = new HashSet<dAvailableTable>();
            this.mTableCell = new HashSet<mTableCell>();
            this.mTableDimensionSet = new HashSet<mTableDimensionSet>();
            this.mTaxonomyTable = new HashSet<mTaxonomyTable>();
            this.mAxis = new HashSet<mAxis>();
            this.vValidationRule = new HashSet<vValidationRule>();
        }
    
        public long TableID { get; set; }
        public string TableCode { get; set; }
        public string TableLabel { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string XbrlFilingIndicatorCode { get; set; }
        public string XbrlTableCode { get; set; }
        public Nullable<long> ConceptID { get; set; }
        public string YDimVal { get; set; }
        public string ZDimVal { get; set; }
    
        public virtual ICollection<dAvailableTable> dAvailableTable { get; set; }
        public virtual ICollection<mTableCell> mTableCell { get; set; }
        public virtual ICollection<mTableDimensionSet> mTableDimensionSet { get; set; }
        public virtual ICollection<mTaxonomyTable> mTaxonomyTable { get; set; }
        public virtual ICollection<mAxis> mAxis { get; set; }
        public virtual ICollection<vValidationRule> vValidationRule { get; set; }
    }
}
