//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ucGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ucGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import Project=&quot;$(MSBuildToolsPath)\Microsoft.CSharp.targets&quot; /&gt;
        ///  &lt;!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
        ///       Other similar extension points exist, see Microsoft.Common.targets.
        ///  &lt;Target Name=&quot;BeforeBuild&quot;&gt;
        ///  &lt;/Target&gt;
        ///  &lt;Target Name=&quot;AfterBuild&quot;&gt;
        ///  &lt;/Target&gt;
        ///  --&gt;
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string ProjectEnd {
            get {
                return ResourceManager.GetString("ProjectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;.
        /// </summary>
        internal static string ProjectStart1 {
            get {
                return ResourceManager.GetString("ProjectStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///    &lt;RootNamespace&gt;SolvencyII.Extensibility&lt;/RootNamespace&gt;.
        /// </summary>
        internal static string ProjectStart2 {
            get {
                return ResourceManager.GetString("ProjectStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TargetFrameworkVersion&gt;v3.5&lt;/TargetFrameworkVersion&gt;
        ///    &lt;FileAlignment&gt;512&lt;/FileAlignment&gt;
        ///    &lt;TargetFrameworkProfile /&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;PropertyGroup Condition=&quot; &apos;$(Configuration)|$(Platform)&apos; == &apos;Debug|AnyCPU&apos; &quot;&gt;
        ///    &lt;DebugSymbols&gt;true&lt;/DebugSymbols&gt;
        ///    &lt;DebugType&gt;full&lt;/DebugType&gt;
        ///    &lt;Optimize&gt;false&lt;/Optimize&gt;
        ///    &lt;OutputPath&gt;bin\Debug\&lt;/OutputPath&gt;
        ///    &lt;DefineConstants&gt;DEBUG;TRACE&lt;/DefineConstants&gt;
        ///    &lt;ErrorReport&gt;prompt&lt;/ErrorReport&gt;
        ///    &lt;WarningLevel&gt;4&lt;/WarningLevel&gt;
        ///  &lt;/Propert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectStart3 {
            get {
                return ResourceManager.GetString("ProjectStart3", resourceCulture);
            }
        }
    }
}
